name: run python
on:
    push:

jobs:
    build:
        name: run py1
        runs-on: ubuntu-latest
        steps:
        - uses:actions/chexkout@v2
        - name: run python
          run:
            python3 test.py   # test          